/** @format */

const ActionTypes = {
  SET_PINNED_POST: "SET_PINNED_POST",
  GROUP_NEW_POSTS: "GROUP_NEW_POSTS",
  GROUP_PUT_POSTS_LAST: "GROUP_PUT_POSTS_LAST",
  PUT_POSTS: "PUT_POSTS",
  UPDATE_POST: "UPDATE_POST",
  DELETE_POST: "DELETE_POST",
  ADD_EVENT: "ADD_EVENT",
  ADD_NEW_EVENT: "ADD_NEW_EVENT",
  REMOVE_EVENT: "REMOVE_EVENT",
  ADD_NEW_POST: "ADD_NEW_POST",
  ADD_GROUP_POST_SPAM: "ADD_GROUP_POST_SPAM",
  REMOVE_GROUP_POST_SPAM: "REMOVE_GROUP_POST_SPAM",

  ADD_GROUP_POST: "ADD_GROUP_POST",
  APPEND_GROUP_POST: "APPEND_GROUP_POST",

  SET_GROUP_POSTS: "SET_GROUP_POSTS",
  APPEND_SINGLE_POST: "APPEND_SINGLE_POST",
  APPEND_GROUP_POSTS: "APPEND_GROUP_POSTS",

  ADD_EVENTS: "ADD_EVENTS",
  PUT_EVENT_FIRST: "PUT_EVENT_FIRST",

  UPDATE_GROUP_POST: "UPDATE_GROUP_POST",
};

export default ActionTypes;
