const ActionTypes = {
  USER_SEARCH_KEY: "USER_SEARCH_KEY",
  ALL_SEARCH: "ALL_SEARCH",
  POST_SEARCH: "POST_SEARCH",
  BLOCK_SAERCH: "BLOCK_SAERCH",
  PEOPLE_SEARCH: "PEOPLE_SEARCH",
  RECENT_SEARCH: "RECENT_SEARCH",
  DELETE_RECENT_SEARCH: "DELETE_RECENT_SEARCH"
}

export default ActionTypes;