const ActionTypes = {
  ADD_NEW_RECOMENDED_GROUP: 'ADD_NEW_RECOMENDED_GROUP',
  ADD_MY_GROUP: "ADD_MY_GROUP",
  ADD_JOIN_GROUP: "ADD_JOIN_GROUP",
  SELECT_SINGLE_GROUP: 'SELECT_SINGLE_GROUP',
  SET_GROUP_DATA: "SET_GROUP_DATA",
  SET_UPDATE_GROUP_DATA: "SET_UPDATE_GROUP_DATA",
  ADD_GROUP_POST: "ADD_GROUP_POST",
  UPDATE_GROUP_POST: "UPDATE_GROUP_POST",
  DELETE_GROUP_POST_DATA: "DELETE_GROUP_POST_DATA",
  ADD_GROUP_COMMENTS: "ADD_GROUP_COMMENTS",
  UPDATE_GROUP_COMMENTS: "UPDATE_GROUP_COMMENTS",
  DELETE_GROUP_COMMENT: "DELETE_GROUP_COMMENT",
  SET_SINGLE_GROUP_DATA: "SET_SINGLE_GROUP_DATA",

  ADD_BLOCKS: "ADD_BLOCKS",
  ADD_MY_BLOCK: "ADD_MY_BLOCK",
  REMOVE_MY_BLOCK: "REMOVE_MY_BLOCK",

  ADD_JOIN_BLOCK: "ADD_JOIN_BLOCK",
  REMOVE_JOIN_BLOCK: "REMOVE_JOIN_BLOCK",

}

export default ActionTypes;