/** @format */

const ActionTypes = {
  SET_PINNED_POST: "SET_PINNED_POST",
  NEW_POSTS: "NEW_POSTS",
  PUT_POSTS_LAST: "PUT_POSTS_LAST",
  PUT_POSTS: "PUT_POSTS",
  UPDATE_POST: "UPDATE_POST",
  DELETE_POST: "DELETE_POST",
  ADD_COMMENTS: "ADD_COMMENTS",
  UPDATE_COMMENT: "UPDATE_COMMENT",
  SELECT_POST: "SELECT_POST",
  REMOVE_POSTS: "REMOVE_POSTS",

  ADD_NOTOFICATION_POST: "ADD_NOTOFICATION_POST",
  REMOVE_NOTIFICATION_POST: "REMOVE_NOTIFICATION_POST",
};

export default ActionTypes;
