/** @format */

const ActionTypes = {
  PUT_NOTIFICATION: "PUT_NOTIFICATION",
  UPDATE_NOTIFICATION: "UPDATE_NOTIFICATION",
  NEW_NOTIFICATION: "NEW_NOTIFICATION",

  SET_NOTIFICATION_COUNT: "SET_NOTIFICATION_COUNT",
  UPDATE_NOTIFICATION_COUNT: "UPDATE_NOTIFICATION_COUNT",
};

export default ActionTypes;
