/** @format */

const ActionTypes = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  ADD_TO_LIKE: "ADD_TO_LIKE",
  REMOVE_TO_LIKE: "REMOVE_TO_LIKE",
  USER_DISLIKES: "USER_DISLIKES",
  ADD_TO_SPAM: "ADD_TO_SPAM",
  REMOVE_TO_SPAM: "REMOVE_TO_SPAM",
  ADD_TO_SHARES: "ADD_TO_SHARES",
  POLL_VOTE: "POLL_VOTE",
  REMOVE_TO_SHARES: "REMOVE_TO_SHARES",
  ADD_TO_DISLIKES: "ADD_TO_DISLIKES",
  REMOVE_TO_DISLIKES: "REMOVE_TO_DISLIKES",
  CURRENT_USER: "CURRENT_USER",
  ADD_FOLLOWER: "ADD_FOLLOWER",
  REMOVE_FOLLOWER: "REMOVE_FOLLOWER",
  UPDATE_USER: "UPDATE_USER",

  ADD_BOOKMARK: "ADD_BOOKMARK",
  REMOVE_BOOKMARK: "REMOVE_BOOKMARK",

  HIDE_USER: "HIDE_USER",
  UNHIDE_USER: "UNHIDE_USER",

  // *** lIKE
  APPEND_LIKES: "APPEND_LIKES",
  REMOVE_LIKES: "REMOVE_LIKES",

  // *** DISLIKES
  APPEND_DISLIKES: "APPEND_DISLIKES",
  REMOVE_DISLIKES: "REMOVE_DISLIKES",

  APPEND_HEART: "APPEND_HEART",
  REMOVE_HEART: "REMOVE_HEART",

  // *** FUNNY
  APPEND_HAHA: "APPEND_HAHA",
  REMOVE_HAHA: "REMOVE_HAHA",

  // *** ANGRY
  APPEND_ANGRY: "APPEND_ANGRY",
  REMOVE_ANGRY: "REMOVE_ANGRY",

  APPEND_PARTY: "APPEND_PARTY",
  REMOVE_PARTY: "REMOVE_PARTY",

  ADD_BLOCKCAST: "ADD_BLOCKCAST",
  REMOVE_BLOCKCAST: "REMOVE_BLOCKCAST",

  ADD_POST_SPAM: "ADD_POST_SPAM",
  REMOVE_POST_SPAM: "REMOVE_POST_SPAM",

  // Comment
  ADD_COMMENT_SPAM: "ADD_COMMENT_SPAM",
  REMOVE_COMMENT_SPAM: "REMOVE_COMMENT_SPAM",
  ADD_COMMENT_LIKE: "ADD_COMMENT_LIKE",
  REMOVE_COMMENT_LIKE: "REMOVE_COMMENT_LIKE",
  ADD_COMMENT_DISLIKE: "ADD_COMMENT_DISLIKE",
  REMOVE_COMMENT_DISLIKE: "REMOVE_COMMENT_DISLIKE",

  // News post
  ADD_RELIABLE: "ADD_RELIABLE",
  REMOVE_RELIABLE: "REMOVE_RELIABLE",

  ADD_INTEREST: "ADD_INTEREST",
  REMOVE_INTEREST: "REMOVE_INTEREST",

  ADD_FAKE: "ADD_FAKE",
  REMOVE_FAKE: "REMOVE_FAKE",

  // Informative Post
  ADD_HELPFUL: "ADD_HELPFUL",
  REMOVE_HELPFUL: "REMOVE_HELPFUL",

  ADD_UNHELPFUL: "ADD_UNHELPFUL",
  REMOVE_UNHELPFUL: "REMOVE_UNHELPFUL",

  ADD_MISLEADING: "ADD_MISLEADING",
  REMOVE_MISLEADING: "REMOVE_MISLEADING",

  // Announcement
  ADD_LIKE_ANNOUNCEMENT: "ADD_LIKE_ANNOUNCEMENT",
  REMOVE_LIKE_ANNOUNCEMENT: "REMOVE_LIKE_ANNOUNCEMENT",

  ADD_IMPORTENT_ANNOUNCEMENT: "ADD_IMPORTENT_ANNOUNCEMENT",
  REMOVE_IMPORTENT_ANNOUNCEMENT: "REMOVE_IMPORTENT_ANNOUNCEMENT",

  // Event
  ADD_INTEREST_EVENT: "ADD_INTEREST_EVENT",
  REMOVE_INTEREST_EVENT: "REMOVE_INTEREST_EVENT",

  ADD_NOT_INTEREST_EVENT: "ADD_NOT_INTEREST_EVENT",
  REMOVE_NOT_INTEREST_EVENT: "REMOVE_NOT_INTEREST_EVENT",

  ADD_JOIN_EVENT: "ADD_JOIN_EVENT",
  REMOVE_JOIN_EVENT: "REMOVE_JOIN_EVENT",

  // Block & Blockcast
  ADD_JOIN_BLOCK: "ADD_JOIN_BLOCK",
  REMOVE_JOIN_BLOCK: "REMOVE_JOIN_BLOCK",
};

export default ActionTypes;
